'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
format,getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";var __name__="AinuCount";export var counters=["","sine","tu","re","ine","asikne","iwan","arwan","tupesan","sinepesan","wan"];export var numbers=["","sinep","tup","rep","inep","asik","iwan","arwan","tupes","sinepes","wanpe"];export var counterThing=
function(){while(true){var x=input("Choose one: (n)umber, (t)hings in general, (p)ersons, (d)ays, t(i)mes, or (o)thers? :");if(x=="n")return"number";if(x=="t")return"things";if(x=="p")return"persons";if(x=="d")return"days";if(x=="i")return"times";if(x=="o")return"others";print("Please type n, t, p, d, i, or o.")}};export var thingName=function(){var x=input("Input your words :");return x};export var countNumber=function(){while(true){var x=input("Input your count number (1-200) :");try{var val=int(x);
if(val>0&&val<=200)return val;else print("Please input an integers between 1 and 200.")}catch(__except0__){if(isinstance(__except0__,ValueError))print("Please input an integers between 1 and 200.");else throw __except0__;}}};export var dialect=function(){while(true){var x=input("(s)aru, or (i)shikari? :");if(x=="s")return"saru";if(x=="i")return"ishikari";print("Please type s, or i.")}};export var numberWords=function(num,kind,word,dlct){if(kind=="number"){if(num>0&&num<=10)return numbers[num];if(num==
20)return"hot"}if(kind=="things"){if(num>0&&num<=5)return counters[num]+"p";if(num>5&&num<=10)return counters[num]+"pe";if(num==20){if(dlct=="ishikari")return"hot";return"hotnep"}}if(kind=="persons"){if(num>0&&num<=5)return counters[num]+"n";if(num>5&&num<=10)return counters[num]+"iw";if(num==20){if(dlct=="ishikari")return"hot";return"hotnen"}}if(kind=="days"){var word="to";if(num==2)return"tutko";if(num==3)return"rerko";if(num>3&&dlct=="saru")var word="rerko"}if(kind=="times"){var word="suy";if(num==
1)return"arsuy"}if(num>0&&num<=10)return counters[num]+" "+word;if(num==20){if(dlct=="ishikari")return"hot "+word;return"hotne "+word}};export var numberStrings=function(num,kind,word,dlct){if(kind=="number"&&num==10)return"to";var z="";if(__mod__(num,10)!=0){z+=numberWords(__mod__(num,10),kind,word,dlct);if(num>10)z+=" ikasma ";else return z}var tmp=int(num/10);var ten=numberWords(10,kind,word,dlct);var twenty=numberWords(20,kind,word,dlct);if(dlct=="ishikari"){if(tmp>9){if(int(tmp/10)>1)z+=counters[int(tmp/
10)];z+="atuyta "}var tmp=__mod__(tmp,10);if(tmp==1)z+=ten;else if(tmp==2)z+=twenty;else if(tmp==0)if(kind=="days")z+="to";else if(kind=="times")z+="suy";else if(kind=="others")z+=word;else var z=z.__getslice__(0,-1,1);else z+=counters[int(tmp)]+twenty;return z}if(tmp==2)z+=twenty;else if(__mod__(tmp,2)==0)z+=counters[int(tmp/2)]+twenty;else if(tmp==1)z+=ten;else if(__mod__(tmp+1,2)==0)z+=ten+" e"+counters[int(tmp/2)+1]+twenty;return z};export var cli_main=function(){var word="";var kind=counterThing();
if(kind=="others")var word=thingName();var num=countNumber();var dlct=dialect();print(numberStrings(num,kind,word,dlct))};if(__name__=="__main__")cli_main();

//# sourceMappingURL=AinuCount.map